title: Krauter
modelClass: JumpLink\KrauterVonAbisZ\Models\Kraut
list: $/jumplink/krautervonabisz/models/kraut/columns.yaml
recordUrl: 'jumplink/krautervonabisz/krauter/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
