plugin:
    name: 'jumplink.krautervonabisz::lang.plugin.name'
    description: 'jumplink.krautervonabisz::lang.plugin.description'
    author: 'Marc Wensauer'
    icon: oc-icon-book
    homepage: ''
navigation:
    main-menu-item:
        label: 'Kräuter Lexicon'
        url: jumplink/krautervonabisz/krauter
        icon: icon-book
        sideMenu:
            side-menu-item:
                label: Kräuter
                url: jumplink/krautervonabisz/krauter
                icon: icon-bookmark
